# Generated by Django 3.1 on 2020-08-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('width', models.IntegerField(default=100)),
                ('height', models.IntegerField(default=100)),
                ('depth', models.IntegerField(default=100)),
                ('color', models.CharField(max_length=50)),
                ('wireFrame', models.BooleanField(default=True)),
                ('size', models.IntegerField(default=5)),
                ('animationX', models.IntegerField(default=0.01)),
                ('animationY', models.IntegerField(default=0.02)),
            ],
        ),
    ]
